### ISSUE TITLE
connect to db from test app

### ISSUE THREAD

**Issue by tomdavidson** [byu-oit-appdev/docker-node-oracledb#1]
Can not connect with the easy connect string in a test node app to on prem db or to a db docker service.  The error is "ORA-12154: TNS:could not resolve the connect identifier specified".

For the test/, I am using docker compose to build the parent image, the child image / node app, and I link to a 11g container. I have commented out the db service and have attempted to connect to on prem db. The node app to test the connection doesn't do anything but try to establish the connection. 

This can be replicated with `docker-compose up` from test/

**Comment by bwinterton** [comment]
This is my connection string that worked 
`10.211.0.76:31200/cescpy1.byu.edu`

**Comment by tomdavidson** [comment]
#3 closes. was a reachability issue with onprem firewall.
